# Developed by Eng Mouaz M AlShahmeh
name: quizu_flutter
description: Developed by Eng Mouaz M AlShahmeh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_riverpod: ^1.0.4
  go_router: ^5.0.1
  share_plus: ^4.4.0
  shared_preferences: ^2.0.15
  pin_code_fields: ^7.4.0
  slide_countdown: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
